# Generated by Django 3.0.5 on 2020-10-03 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0002_auto_20201003_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
