# Generated by Django 3.0.5 on 2020-10-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0004_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='imagen_usuario',
            field=models.ImageField(default='default', upload_to='Cursos/usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(upload_to='Cursos/curso'),
        ),
    ]
