# Generated by Django 3.0.5 on 2020-10-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0005_auto_20201004_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='curso',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='comentarios',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='imagen_usuario',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='content',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
