# Generated by Django 3.0.5 on 2020-10-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0007_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='content',
            new_name='contenido',
        ),
    ]
