# Generated by Django 3.0.5 on 2020-10-04 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0008_auto_20201004_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='contenido',
            new_name='content',
        ),
    ]
