# Generated by Django 3.0.5 on 2020-10-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0012_auto_20201004_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='contador_comentarios',
        ),
    ]
